version: '2'
services:
    db:
        build: ./docker/database
        ports:
            - "5532:5432"
        environment:
            POSTGRES_DB: gapi
            POSTGRES_USER: gapi
            POSTGRES_PASSWORD: gapi
        volumes:
            - ./application/var/postgresql/:/var/lib/postgresql/data/
        hostname: db

    php:
        build: ./docker/php
        expose:
            - "9000"
        environment:
            SYMFONY__ENV: dev
            SYMFONY__DEBUG: 1
            SYMFONY__DATABASE__HOST: db
            SYMFONY__DATABASE__PORT: 5432
            SYMFONY__DATABASE__NAME: gapi
            SYMFONY__DATABASE__USER: gapi
            SYMFONY__DATABASE__PASSWORD: gapi
        volumes:
            - ./application:/var/www
        links:
            - db
        tty: true
        hostname: app

    nginx:
        build: ./docker/nginx
        environment:
            NGINX_HOST: gapi.dev
        ports:
            - "8180:80"
        links:
            - php
        volumes:
            - ./logs:/var/log/nginx